### ISSUE TITLE
using different port with remote server alias

### ISSUE THREAD

**Issue by rptaylor** [cvmfs-contrib/cvmfs-servermon#38]
Hi @DrDaveD 

With this in api.conf:
```
serveralias arbutus=cvmfs-s1-arbutus.computecanada.ca:8000
```

Looks like it should work based on 
```
# Available options are:
#   serveralias <aliasname>=<fully.qualified.domain.name[:port][/subdirectory]>
```

but
http://cvmfs-s1dev-arbutus.computecanada.ca:8000/cvmfsmon/api/v1.0/all&format=details&server=arbutus
```
http://cvmfs-s1-arbutus.computecanada.ca/cvmfs/info/v1/repositories.json error: <urlopen error timed out>
```

Instead it should be trying to access http://cvmfs-s1-arbutus.computecanada.ca:8000/cvmfs/info/v1/repositories.json

**Comment by DrDaveD** [comment]
Or maybe it's an el8-only.

**Comment by rptaylor** [comment]
Oh, yes it works after waiting a bit. Thanks.

**Comment by rptaylor** [comment]
Although it was still very strange because it clearly was reading the config to determine that the alias 'arbutus' was cvmfs-s1-arbutus.computecanada.ca:8000 , but not using the port number in there. I didn't change anything but it started working awhile later.
