### ISSUE TITLE
servermon for EL9

### ISSUE THREAD

**Issue by rptaylor** [cvmfs-contrib/cvmfs-servermon#44]
Hi @DrDaveD , will servermon be available for EL9? I don't see EL9 packages here: http://download.opensuse.org/repositories/home:/cvmfs:/contrib/

**Comment by DrDaveD** [comment]
Very unfortunately the OpenSUSE Build Service does not yet support an EL9 build target.  I don't know why or when or even if that will be fixed, or what to do about it if it isn't fixed.

**Comment by DrDaveD** [comment]
Hang on, it's not in the normal list of OBS distributions, but there is a RockyLinux:9 project.  I will try that.

**Comment by DrDaveD** [comment]
It's now in https://mirrorcache-us.opensuse.org/repositories/home:/cvmfs:/contrib/AlmaLinux_9/noarch/.  Please test it.

**Comment by DrDaveD** [comment]
I tested it and found a couple of issues, now fixed in version 1.25.  Please let me know how that version works for you.

**Comment by DrDaveD** [comment]
I am assuming it works, closing.
